### ISSUE TITLE
error: 'jit_compiler' was not declared in this scope

### ISSUE THREAD

**Issue by vdudouyt** [goccy/gperl#14]
I'm getting the following errors while trying to compile on Linux (tried with GCC 4.6.1 and 4.8.2):

gen_vm.cpp:1054:2: error: 'jit_compiler' was not declared in this scope
gen_vm.cpp:1109:2: error: 'jit_compiler' was not declared in this scope
gen_vm.cpp:1124:2: error: 'jit_compiler' was not declared in this scope
gen_vm.cpp:1139:2: error: 'jit_compiler' was not declared in this scope
gen_vm.cpp:1154:2: error: 'jit_compiler' was not declared in this scope
gen_vm.cpp:1169:2: error: 'jit_compiler' was not declared in this scope
gen_fast_vmcode.cpp:3526:2: error: 'jit_compiler' was not declared in this scope
gen_fast_vmcode.cpp:3531:2: error: 'jit_compiler' was not declared in this scope

Are you able to compile #4ba56a67 by yourself, and might this be a platform / compiler-specific issue?

Thanks
